---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guo23.
--- DateTime: 2023/4/3 21:25
---
TestOne = {}
local this = TestOne
local manager
function this.Awake()
    print("Hello, Lua")
    
end